# Generated by Django 3.0.1 on 2019-12-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Russian'), (1, 'Coding')], default=0),
        ),
    ]
