# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
