# Generated by Django 3.0.1 on 2020-03-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191231_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vocab',
            field=models.IntegerField(choices=[(0, 'Russian'), (1, 'Coding')], default=0),
        ),
    ]
