# Generated by Django 3.0.1 on 2020-03-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vocab',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
