# Generated by Django 3.0.1 on 2020-03-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='russian',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
